python SupportingEndpoints/MachineLearningForGraphing.py
python SupportingEndpoints/GenerateModelForGraphing.py
python SupportingEndpoints/GenerateDMDModel.py
python SupportingEndpoints/GenerateSindyModel.py

python SupportingEndpoints/Test_Retrainer.py